"""initial

Revision ID: b8d5cf329c5a
Revises: 
Create Date: 2026-09-05 02:58:59.973367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('coingecko_id', sa.String(length=64), nullable=True),
    sa.Column('icon_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    op.create_table('exchanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('supports_testnet', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('global_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_market_cap_usd', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('total_volume_24h_usd', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('market_cap_change_24h_pct', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('btc_dominance', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('eth_dominance', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('fng_value', sa.Integer(), nullable=True),
    sa.Column('fng_label', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_stats_captured_at'), 'global_stats', ['captured_at'], unique=False)
    op.create_table('timeframes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=False),
    sa.Column('seconds', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('totp_secret_enc', sa.Text(), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_username', sa.String(length=255), nullable=True),
    sa.Column('telegram_link_code', sa.String(length=32), nullable=True),
    sa.Column('telegram_link_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('base_currency', sa.String(length=8), nullable=False),
    sa.Column('theme', sa.String(length=16), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_user_time', 'audit_log', ['user_id', 'created_at'], unique=False)
    op.create_table('exchange_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('api_key_enc', sa.Text(), nullable=False),
    sa.Column('api_secret_enc', sa.Text(), nullable=False),
    sa.Column('api_key_masked', sa.String(length=64), nullable=False),
    sa.Column('is_testnet', sa.Boolean(), nullable=False),
    sa.Column('requested_trading', sa.Boolean(), nullable=False),
    sa.Column('allow_trading', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exchange_id', 'label')
    )
    op.create_table('invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by_user_id', sa.Integer(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['used_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('login_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('base_asset_id', sa.Integer(), nullable=False),
    sa.Column('quote_asset_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('raw_symbol', sa.String(length=64), nullable=False),
    sa.Column('market_type', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('price_precision', sa.Integer(), nullable=True),
    sa.Column('amount_precision', sa.Integer(), nullable=True),
    sa.Column('min_amount', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('tick_size', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['base_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ),
    sa.ForeignKeyConstraint(['quote_asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange_id', 'symbol', 'market_type')
    )
    op.create_table('notification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_type', 'channel')
    )
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_user_time', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('total_usd', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('breakdown', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_portfolio_snapshots_user_time', 'portfolio_snapshots', ['user_id', 'captured_at'], unique=False)
    op.create_table('user_recovery_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('alert_type_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trigger_count', sa.Integer(), nullable=False),
    sa.Column('trigger_limit', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notify_web', sa.Boolean(), nullable=False),
    sa.Column('notify_telegram', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_type_id'], ['alert_types.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange_account_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('free', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('locked', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('total', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('usd_value', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['exchange_account_id'], ['exchange_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange_account_id', 'asset_id')
    )
    op.create_table('candles',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('timeframe_id', sa.Integer(), nullable=False),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('high', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('low', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('close', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('volume', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timeframe_id'], ['timeframes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('market_id', 'timeframe_id', 'open_time')
    )
    op.create_index('ix_candles_lookup', 'candles', ['market_id', 'timeframe_id', 'open_time'], unique=False)
    op.create_table('market_tickers',
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('last', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('bid', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('ask', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('high_24h', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('low_24h', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('volume_24h', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('change_24h_pct', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('market_id')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange_account_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('amount', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('mark_price', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('unrealized_pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('leverage', sa.Integer(), nullable=True),
    sa.Column('cost_basis_complete', sa.Boolean(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exchange_account_id'], ['exchange_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange_account_id', 'market_id', 'side')
    )
    op.create_table('signal_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('market_id', sa.Integer(), nullable=True),
    sa.Column('timeframe_id', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('evaluation_horizon_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timeframe_id'], ['timeframes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trades',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('exchange_account_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=True),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('amount', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('cost', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('fee', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('fee_asset_id', sa.Integer(), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exchange_account_id'], ['exchange_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fee_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange_account_id', 'external_id')
    )
    op.create_index('ix_trades_account_time', 'trades', ['exchange_account_id', 'executed_at'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'market_id')
    )
    op.create_table('alert_triggers',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('delivered_web', sa.Boolean(), nullable=False),
    sa.Column('delivered_telegram', sa.Boolean(), nullable=False),
    sa.Column('delivery_error', sa.Text(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alert_triggers_time', 'alert_triggers', ['alert_id', 'triggered_at'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('timeframe_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('indicators', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('candle_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['signal_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timeframe_id'], ['timeframes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signals_market_time', 'signals', ['market_id', 'created_at'], unique=False)
    op.create_table('strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('signal_rule_id', sa.Integer(), nullable=False),
    sa.Column('exchange_account_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('position_size_pct', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('stop_loss_pct', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('take_profit_pct', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('max_pct_per_trade', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('daily_loss_limit_pct', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('live_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exchange_account_id'], ['exchange_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['signal_rule_id'], ['signal_rules.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_journal',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bot_journal_strategy_time', 'bot_journal', ['strategy_id', 'created_at'], unique=False)
    op.create_table('bot_orders',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('exchange_account_id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('amount', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('price', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('external_order_id', sa.String(length=64), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['exchange_account_id'], ['exchange_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bot_orders_strategy_time', 'bot_orders', ['strategy_id', 'opened_at'], unique=False)
    op.create_table('risk_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('trading_day', sa.Date(), nullable=False),
    sa.Column('realized_pnl_pct', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('trades_count', sa.Integer(), nullable=False),
    sa.Column('is_halted', sa.Boolean(), nullable=False),
    sa.Column('halted_reason', sa.Text(), nullable=True),
    sa.Column('halted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'trading_day')
    )
    op.create_table('signal_outcomes',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('horizon_minutes', sa.Integer(), nullable=False),
    sa.Column('price_after', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('pnl_pct', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('is_success', sa.Boolean(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signal_outcomes')
    op.drop_table('risk_state')
    op.drop_index('ix_bot_orders_strategy_time', table_name='bot_orders')
    op.drop_table('bot_orders')
    op.drop_index('ix_bot_journal_strategy_time', table_name='bot_journal')
    op.drop_table('bot_journal')
    op.drop_table('strategies')
    op.drop_index('ix_signals_market_time', table_name='signals')
    op.drop_table('signals')
    op.drop_index('ix_alert_triggers_time', table_name='alert_triggers')
    op.drop_table('alert_triggers')
    op.drop_table('watchlist_items')
    op.drop_index('ix_trades_account_time', table_name='trades')
    op.drop_table('trades')
    op.drop_table('signal_rules')
    op.drop_table('positions')
    op.drop_table('market_tickers')
    op.drop_index('ix_candles_lookup', table_name='candles')
    op.drop_table('candles')
    op.drop_table('balances')
    op.drop_table('alerts')
    op.drop_table('user_recovery_codes')
    op.drop_index('ix_portfolio_snapshots_user_time', table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_index('ix_notifications_user_time', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('notification_settings')
    op.drop_table('markets')
    op.drop_table('login_events')
    op.drop_table('invites')
    op.drop_table('exchange_accounts')
    op.drop_index('ix_audit_log_user_time', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_table('timeframes')
    op.drop_index(op.f('ix_global_stats_captured_at'), table_name='global_stats')
    op.drop_table('global_stats')
    op.drop_table('exchanges')
    op.drop_table('assets')
    op.drop_table('alert_types')
    # ### end Alembic commands ###
