"""ticker quote volume

Turnover in the quote currency: sorting markets by volume in coins is meaningless, since
memecoin amounts are measured in trillions.

Revision ID: d67a112f641f
Revises: 0002
Create Date: 2026-09-05 15:24:29.576635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_tickers', sa.Column('quote_volume_24h', sa.Numeric(precision=20, scale=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_tickers', 'quote_volume_24h')
    # ### end Alembic commands ###
