"""notification delivery

Отметка о доставке уведомления в Telegram: запись события отделена от
отправки, чтобы алерт не терялся при недоступном боте.

Revision ID: 9240f435a244
Revises: 0004
Create Date: 2026-09-05 16:05:04.035659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0005'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default обязателен: в таблице уже есть строки, и NOT NULL
    # без значения по умолчанию свалил бы миграцию на боевой базе.
    op.add_column(
        'notifications',
        sa.Column(
            'delivered_telegram',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.add_column('notifications', sa.Column('delivery_error', sa.Text(), nullable=True))
    # Значение по умолчанию нужно было только для заполнения старых строк:
    # дальше его проставляет приложение.
    op.alter_column('notifications', 'delivered_telegram', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'delivery_error')
    op.drop_column('notifications', 'delivered_telegram')
    # ### end Alembic commands ###
