"""wide numeric for market cap

Total market cap is measured in trillions, while Numeric(20, 8) holds less than 10^12 -
inserts with live CoinGecko data failed with numeric field overflow.

Revision ID: 06ea044f3464
Revises: 0005
Create Date: 2026-09-05 16:20:24.846654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0006'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('global_stats', 'total_market_cap_usd',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               type_=sa.Numeric(precision=30, scale=2),
               existing_nullable=True)
    op.alter_column('global_stats', 'total_volume_24h_usd',
               existing_type=sa.NUMERIC(precision=20, scale=8),
               type_=sa.Numeric(precision=30, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('global_stats', 'total_volume_24h_usd',
               existing_type=sa.Numeric(precision=30, scale=2),
               type_=sa.NUMERIC(precision=20, scale=8),
               existing_nullable=True)
    op.alter_column('global_stats', 'total_market_cap_usd',
               existing_type=sa.Numeric(precision=30, scale=2),
               type_=sa.NUMERIC(precision=20, scale=8),
               existing_nullable=True)
    # ### end Alembic commands ###
